---
title: "DDM Evaluation Quetelet"
author: "José H C Monteiro da Silva"
date: "11/27/2020"
output: pdf_document
---

```{r setup, include=FALSE}
rm(list = ls())
graphics.off()

require(dplyr)
require(data.table)
require(DDM)
require(ggplot2)

load('DATA/DATA_POP_2000.RData')
dat2000 <- 
  TAB[ , .( ufcode = UF,
            urb = ifelse( RUR_URB == '1', 'urb', 'rur' ),
            sex = ifelse( SEXO == 1, 'm', 'f' ),
            age = as.numeric( IDADE ),
            pop = N_PES ) ] %>%
  .[ , .( pop1 = sum( pop ) ),
     .( urb, sex, age ) ]
rm( TAB )

dat2010 <- 
  readRDS( 'DATA/BRCENSUS2010AdjDeaths.rds' ) %>%
  .[ , .( urb, sex, age = as.numeric( age ), 
          pop, deaths ) ] %>%
  .[ , .( pop2 = sum( pop ),
          deaths = sum( deaths ) ),
     .( urb, sex, age ) ]

dat_ddm <- 
  merge(
    dat2000,
    dat2010,
    by = c( 'urb', 'sex', 'age' )
  ) %>%
  .[ , date1 := as.Date( '2000-07-31' ) ] %>%
  .[ , date2 := as.Date( '2010-07-31' ) ] %>%
  .[ , deaths := ( deaths / pop2 ) * sqrt( pop1 * pop2 ) ] %>%
  .[ , .(
    cod = urb,
    sex, age,
    date1, pop1,
    date2, pop2,
    deaths ) ]
```

# Results DDM

## Population counts 2000 and 2010
```{r popcounts}

dat2000[, .( pop = sum( pop1 ) ), .( urb ) ]

dat2010[, .( pop = sum( pop2 ) ), .( urb ) ]

```

## DDM Females
```{r ddm females}
ddm( dat_ddm[ sex == 'f' ], 
     exact.ages.ggb = seq( 5, 65, 5 ), 
     exact.ages.seg = seq( 25, 65, 5 ),
     deaths.summed = FALSE )
```

## DDM Males
```{r ddm males}
ddm( dat_ddm[ sex == 'm' ], 
     exact.ages.ggb = seq( 5, 65, 5 ), 
     exact.ages.seg = seq( 25, 65, 5 ),
     deaths.summed = FALSE )
```

# Plots

## GGB
```{r ggb, echo=FALSE, fig.width= 6, fig.height= 4,fig.cap='Results GGB by rural-urbal household and sex. Blue line = adjusted curve using age range 15-65.', warning=F}
ggbRes <- 
  rbind(
    ggbMakeColumns( dat_ddm[sex == 'f' & cod == 'rur'] ),
    ggbMakeColumns( dat_ddm[sex == 'f' & cod == 'urb'] ),
    ggbMakeColumns( dat_ddm[sex == 'm' & cod == 'rur'] ),
    ggbMakeColumns( dat_ddm[sex == 'm' & cod == 'urb'] )
  )

  ggplot() +
  geom_text( data = ggbRes,
             aes( x = rightterm, y = leftterm, label = age ),
             size = 3 ) +
  geom_smooth( data = ggbRes[ age %in% 15:65 ],
               aes( x = rightterm, y = leftterm ),
               method = 'lm', se = F,
               size = 1, color = 'navy' ) +
  geom_abline( intercept = 0, slope = 1, 
               size = 0.12, color = 'red', linetype = 'longdash' ) +
  facet_wrap( vars( sex, cod ), nrow = 2 ) +
  theme_light() 

```


## GGB-SEG
```{r ggbseg, echo=FALSE, fig.width=6, fig.height= 3,fig.cap='Results GGB-SEG by rural-urbal household and sex.'}

segRes <- 
  rbind(
    ggbsegMakeColumns( dat_ddm[sex == 'f' & cod == 'rur'],
                       agesFit.ggb = seq( 15, 65, 5 ) ),
    ggbsegMakeColumns( dat_ddm[sex == 'f' & cod == 'urb'],
                       agesFit.ggb = seq( 15, 65, 5 ) ),
    ggbsegMakeColumns( dat_ddm[sex == 'm' & cod == 'rur'],
                       agesFit.ggb = seq( 15, 65, 5 ) ),
    ggbsegMakeColumns( dat_ddm[sex == 'm' & cod == 'urb'],
                       agesFit.ggb = seq( 15, 65, 5 ) )
  )

segRes[age %in% 5:70 ] %>%
  ggplot() +
  geom_hline( yintercept = 1.00, 
              color = 'tomato3', size = 0.15, linetype = 'longdash' ) +
  geom_hline( yintercept = 0.80, 
              color = 'tomato3', size = 0.15, linetype = 'longdash' ) +
  geom_hline( yintercept = 0.60, 
              color = 'tomato3', size = 0.15, linetype = 'longdash') +
  geom_point( aes( x = age, y = Cx,
                   color = sex,
                   shape = cod ) ) +

  scale_color_manual( values = c( 'f' = 'red',
                                  'm' = 'blue' ),
                      labels = c( 'f' = 'Females',
                                  'm' = 'Males' ),
                      name = '' ) +
  scale_shape_manual( values = c( 'urb' = 19,
                                  'rur' = 10 ) ) +
  scale_y_continuous( limits = c( 0, 1 ),
                      breaks = seq( 0, 1, 0.10 ) ) +
  scale_x_continuous( limits = c( 5, 70 ),
                      breaks = seq( 5, 70, 5 ) ) +
  facet_wrap( ~ cod, nrow = 1 ) +
  theme_light() +
  theme( legend.position = 'top' ) 

```