---
title: "Rural-Urban health and mortality differentials in Brazil, 2010-2013"
author: "José H C Monteiro da Silva, Bernardo L. Queiroz, Diana O. Sawyer, Fabiano N. A. Pereira"
date: "03-2020"
output: 
  word_document:
    reference: referencia.docx
bibliography: bibliografia.bib
csl: ejph.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

<!-- The rural-urban mortality differential is a topic of great concern of demography, public health and public policy researchers. Different access to services and public health equipment may reflect in different mortality outcomes for population groups. This is broadly documented in the literature and its results are evident from mortality differentials in terms of geographic location. In this paper we target urban-rural mortality and morbidity differentials in Brazil using the 2010 National Census mortality data and the 2013 National Health Survey (PNS, from portuguese *Pesquisa Nacional de Saúde*) morbidity data.  -->

By the beginning of the urbanization and industrialization processes in the developed Western countries, urban areas exhibited higher mortality rates than their rural counterparts [@davis1973;@woods2003]. Mortality levels among young age-groups (0-14) were more sensitive to the urban environment than adult mortality levels; hence, cities observed higher youth mortality rates than rural areas [@woods2003]. Infant and child mortality rates are affected by wealth and socioeconomic determinants through variables such as sanitation conditions and population dietary intake [@mosley_chen1984]. Cities of the XIX century presented poor living conditions and high population density, contributing to the spread of communicable diseases, responsible for most deaths in urban centers in that period [@davis1973].

In the following periods, this scenario changed considerably. Socioeconomic development and economic growth of Western countries subsidized better living conditions in cities [@preston1975] and these provided resources to overcome communicable diseases deaths and fostered the epidemiological transition by the end of XIX century period [@omran1971]. The differential economic growth between metropolitan and non-metropolitan areas, nevertheless, created gaps in access to public services such as health equipment and transportation that are still a major issue in cities nowadays [@woods2003;@fotso2006;@jedwab_vollrath2019;@torres_etal2019]. In the United States, for example, rural and non-metropolitan residents are in a disadvantaged position in regard to life expectancy and to health indicators [@singh2003;@singh_siahpush2013;@spencer_etal2018;@chen_etal2019;@henning_etal2019]. This negative position in relation to their urban counterparts is followed by other features such as higher health information illiteracy among rural residents, lack of access to health equipment and other kinds of socioeconomic deprivation that are more likely to affect non-metropolitan areas [@singh2003;@strasser2003;@henning_etal2017;@spencer_etal2018;@chen_etal2019;@henning_etal2019;@voigt_etal2019]. 

The debate over urban and rural mortality differentials in developing countries is usually divided in two components: infant/child mortality and adult mortality. Infant and child mortality are more impacted by community-level characteristics and socioeconomic situation [@mosley_chen1984;@gould1998;@sastry2004;@fink_etal2016;@garenne2016]. Latin American countries, for example, present lower urban than rural infant mortality rates, despite most of countries are in a converging trend of urban and rural rates [@garcia2020]. In Brazil, urban areas exhibit an under-five mortality advantage in comparison to the country's rural areas, as a result of its better socioeconomic status such as higher schooling levels and higher access to sanitation and public services in general [@sastry1997;@sastry2004;@soares_etal2016]. 

In spite of the urban advantaged observed in child and infant mortality levels, most studies documented lower adult mortality rates in rural areas of lower income countries [@sastry1997;@gould1998;@sastry2004;@gunther_harttgen2012;@fink_etal2016;@oren2018;@albuquerque2019]. Metropolitan areas of developing countries present high within-urban mortality gaps among social groups due to the unequal access to essencial public services (health equipment, education and sanitation) as a consequence of a rapid urbanization process [@gunther_harttgen2012;@fink_etal2016;@brueckner2019]. Living conditions in these developing urbanized centers deteriorate individuals health and expose them to higher mortality risks compared to their rural counterparts in a similar way as observed in the past for more developed countries, resulting in an urban death penalty [@reher2001].

This is a particular feature of Brazilian mortality differentials. The advantage of urban environments in regard to mortality in Brazil prevails on some specific conditions. @carvalho_wood1978 showed that urban-rural life expectancy differentials favored the urban areas of wealthier social strata whereas the opposite was observed in poor areas of the country in 1960-70 period. Using 2010 National Census mortality data, @albuquerque2019 verified a mortality advantage for rural areas, especially for the male population. He estimated 73.6 and 69.3 life expectancies at birth for rural and urban male population, respectively, and 77.8 and 77.1 life expectancies for females. @pereira2020 disentangled these findings by looking into social groups of different urban areas. He compared Brazilian mortality levels of urban residents from slums and from out of slums with rural residents mortality levels and verified an urban penalty for those living in these marginalized urban environments. The urban periphery of Brazilian metropolitan areas are known for its poor urban assets and damaged social conditions, presenting high violence and criminal rates and deprivation of public assets such as public sanitation [@merrick1985;@worldbank2015]. The result of this scenario is a worsened health and mortality status of the urban adult peripherical population of the country [@pereira_queiroz2016;@albuquerque_etal2017;@pereira2018,@pereira2020]. 

This debate about urban-rural mortality differentials in Brazil has gained momentum over the last years due to the changes proposed in the social security system. Since 1988, rural groups were guaranteed access to almost universal age-retirement pensions at lower ages than urban residents (60/65 for males and 55/60 for females) [@beltrao_etal2000]. During the 1990s and 2000s, the public pension system income played an important role for economically vulnerable rural households and was a main driver of poverty reduction within this population groups, especially in North and Northeast regions [@beltrao_etal2000;@camarano2002;@gori2015]. However, continued deficits of the Brazilian social security system resulted in the need for reforms on age of retirement which brought up the discussion on whether rural residents should continue to retire 5 years before urban residents [@paiva_etal2018]. Estimates of ages at benefit cessation constructed from social security system data are higher for rural residents than for urban residents [@paiva_etal2018]. This result was used as an argument to repeal this lower age of retirement benefit of rural workers [@paiva_etal2018]. Those contraty to this opinion, nevertheless, have highlighted the different access to public health equipment and health disadvantages of the rural population to justify keeping a lower retirement age for rural workers [@arbex_galiza2017].

Such as in the case of USA, Brazilian rural residents experience higher deprivation in access to services and health facilities and usually report worse health status conditions and are in worse economic situation than urban residents [@camarano2002;@wanderley2008;@paiva_etal2018;@arruda_etal2018]. This scenario echos the higher vulnerability condition of rural areas and other territories with lower economic integration [@travassos_etal2006;@soares_etal2016;@viacava_etal2019]. The distance of health equipment, lack of resources to pay for the transportation, the lack of health professionals or unavailability of higher complexity health services are barriers to the access of public health systems by the rural population [@kassouf2005;@travassos_viacava2007;@viacava_etal2019]. This situation is worsened for the elderly, population group with higher demand for such services [@travassos_viacava2007}. Moreover, the access to health services of rural residents relies almost exclusively on the public health system (SUS, from portuguese *Sistema Único de Saúde*) and on visits of family-care doctors of the Family Health Strategy (ESF, from portuguese *Estratégia de Saúde da Família*) while urban residents have higher access to health insurance and to a higher diversity of health equipment from both private and public health systems [@kassouf2005;@malta_etal2016;@albuquerque_etal2017;@arruda_etal2018].

The different tasks and activities demanded by the living environment also shapes the mortality and morbidity outcomes of a population. Rural populations observe higher prevalence of specific disabilities and diseases such as chronic pains, back pains, arthritis and urban populations are usually more susceptible to diabetes, high blood pressure, heart diseases and depression [@camarano2002]. Further, rural residents are more prone to report worsened health status [@camarano2002;@maia_rodrigues2010;@arruda_etal2018;@paiva_etal2018]. @moreira_etal2015 found that back pain, rheumatism, arthritis and high blood pressure were associated to the agricultural activities and results from intense physical effort in work. The difference in social status also plays a key role in the self-perception of health state [@viacava_etal2019]. Then, rural populations usually declare poor health conditions than urban ones [@maia_rodrigues2010;@arruda_etal2018]. However, looking into social groups, rural residents from lower social strata have higher probability of referring a good state of health than their similars from urban areas [@maia_rodrigues2010].

This study aims to provide further information for the discussion on urban-rural mortality differentials. The rural life expectancy advantage expressed in the Brazilian national census of 2010 [@albuquerque2019] may not reflect a real disease free life expectancy or healthy life expectancy advantage, e. g., people from rural areas might live for longer periods, but they would have to live with disabilities that can mitigate their capacity to develop daily activities. In this sense, we investigate the prevalence of some specific diseases in urban and rural populations and construct disease-free life expectancy estimates for both residents using data from the national census of 2010 and from the national health survey (PNS, from portuguese *Pesquisa Nacional de Saúde*) of 2013. Our hypothesis is that urban areas may exhibit relative advantages in disease/disability-free life expectancy than rural areas for health problems related to physical effort while a higher prevalence of chronic diseases may be more harmful in the urban environment. By focusing on adult population estimates, this work contributes to the evaluation of urban environment penalties on adult mortality and morbidity in developing countries by analysing specific groups of diseases and disabilities that result in different mortality outcomes for urban and rural areas [@gunther_harttgen2012]. 

## Materials and Methods

### Data

This paper uses data from Brazilian national census of 2010 and Brazilian national health survey of 2013 to estimate basic life table functions and implement further extensions on these functions for the evaluation of population health state. Both household enquiries are conducted by the Brazilian Institute of Geography and Statistics (IBGE, from portuguese *Instituto Brasileiro de Geografia e Estatística*). 

The PNS was created to describe and assess the health situation and lifestyles of the Brazilian population by asking questions in regard to access and use of services, to preventive actions and also to socio-demographic characteristics [@pns2014;@damacena_etal2015]. The survey also conducted checking on some physical measures - blood pressure, weight, height - and collected biological materials from respondents [@damacena_etal2015]. PNS survey permits to evaluate specific morbidity indicators of the population, such as the prevalence of chronic diseases, by socioeconomic strata or geographic environment (urban-rural) of the household.

The addition of mortality inquiry in the Brazilian 2010 national census represented an opportunity to implement studies and analysis that could not be done by using the mortality information system (SIM, from portuguese *Sistema de Informações sobre Mortalidade*) data from the Ministry of Health. Despite the SIM data quality improvements [@lima_queiroz2014] and coverage expansion of death registers [@queiroz_etal2017], this system data does not provide substantial information about the deceased socioeconomic characteristics which are essential for the evaluation of mortality in subnational population groups [@UN2017;@queiroz_sawyer2012;@queiroz_sacco2018]. 

Therefore, most of the mentioned studies developed about Brazilian socioeconomic differentials in mortality before 2010 national census applied indirect methods to construct estimates using census or household surveys data [@carvalho_wood1978;@merrick1985;@sastry1997;@sastry2004]. The addition of mortality inquiry in the 2010 national census enabled the development of several studies on educational mortality differentials [@silva_etal2016], indigenous groups mortality [@campos_etal2017], socioeconomic strata mortality differentials [@pereira_queiroz2016] and on urban groups mortality differentials [@pereira2018;@pereira2020]. 

<!-- The inclusion of mortality inquiries in national census is a recommendation of the United Nations for countries with deficient register systems [@UN2017]. Several Latin American and Caribbean countries have included a question of deaths in the household within 12 months before the reference period in their national censuses [@queiroz_sacco2018]. Despite some issues, in particular those related to deceases in mono-parental households or deaths that result in breaks in family ties, the mortality inquiry in national censuses is important for performing complex analysis which might not be assessed by national register systems, such as urban-rural mortality differentials [@UN2017;@queiroz_sacco2018]. -->

The national census of 2010 investigated household deaths over the last 12 months before the reference period of the census (August 2009 - July 2010). Household respondents answered questions about age and sex of household's deceases within this period. The use of death counts from national census for computing death rates has the advantage of considering both numerator and denominator from the same data source, which contributes for the robustness of mortality pattern estimation. However, an individual's report on the household's deaths might be mistaken, then mortality levels computed from national census must be corrected. Death counts from national census are under-enumerated in comparison to mortality information system data and present a death coverage rate of about 80-85\%, according to death registration coverage estimation methods [@queiroz_sawyer2012].

### Methods

Our methodological strategy encompasses four stages of analysis: 1) estimation of basic life table functions for each population group (urban and rural residents) from 2010 national census mortality data; 2) estmation and analysis of disease and disability age-specific prevalence data from PNS and national census data on disease and disability prevalence; 3) construction of disease/disability-free life expectancy indicators (also known as health expectancy) for each population group; and 4) decomposition of health expectancy differentials among rural and urban populations in terms of overall mortality profiles contribution and specific morbidity profiles contribution.

#### Correction of mortality levels

As mentioned, Brazilian 2010 national census mortality information has death coverage rates ranging from 80-85\% [@queiroz_sawyer2012]. Since death registry coverage is sensitive to regional inequalities [@queiroz_etal2017], census mortality data might also exhibit this pattern and is very likely to present differences between rural and urban households. Therefore, our first attempt was to estimate death coverage of each of these settings by applying synthetic extinct generations (SEG) [@bennett_horiuchi1981], generalized growth balance (GGB) [@hill1987] and adjusted synthetic extinct generations (SEG-adjusted) [@hill_etal2009] methods built in the R package *DDM* (Death Registration Coverage Estimation) [@riffe_etal2017]. However, all methods presented poor performance, showing much lower and unexpected death coverage in rural areas. We speculate that intense rural exodus to urban areas may affect the estimates and decrease the death coverage rates of rural areas by considering the population reduction due to migration as possible omitted deaths. This bias is a direct result closed population assumption required by these death registration coverage methods.

Then, we addopted a different strategy for completeness of death counts correction. We considered that regional inequalities of death coverage may already account at some extent for urban-rural differences in death coverage, especially because the regions with lower coverage (North and Northeast regions) are the ones with higher proportions of population living in low-density areas [@ibge2017]. Afterwards, we estimated regional death coverage rates (DCR) by the SEG-adjusted method by sex for the five Brazilian regions (North, Northeast, Central-West, Southeast, South). North (DCR males: 0.89, DCR females: 0.92) and Northeast (DCR males: 0.78, DCR females: 0.84) presented the lowest estimated death coverages rates; South (males: 1.05, females: 0.94) and Southeast (males: 0.98, females: 1.03) presented the highest estimates; and Central-West exhibited an intermediate DCR level among the five regions (DCR males: 0.93, DCR females: 0.94). Census death counts were then corrected for each region by dividing the observed death counts by respective DCR. DCR higher than 1 were considered as 1, since there is no evidence that supports a death over-counting in the 2010 national census at any region of the country.

#### Morbidity-free life expectancy estimation by Sullivan method

The Sullivan method of life tables uses data from diseases prevalence to construct a single index of mortality and morbidity, named disease-free life expectancy or health expectancy [@sullivan1971;@andreev_etal2002;@EHEMU2014]. This index provides an estimate of years free of disability that a member of the life table's synthetic cohort would experience if the current age-specific rates of mortality and disease/disability prevalence prevailed throughout the cohort's lifetime [@sullivan1971].  

The basic inputs of the method are the age-specific mortality rates for life table functions estimation and age-specific disease or disability (morbidity) prevalence ($_nP_x$). After the estimation of life table functions using mortality rates as inputs, the complement of the morbidity prevalence (morbidity-free prevalence) are multiplied by the person-years lived ($_nL_x$) for each age group (equation 1).

$$ _nL_x^{SUL} = _nL_x * (1 - _nP_x) $$

The Sullivan person-years lived by the age-group represents the person-years free of morbidity or healthy life years of that age interval. This value is used to estimate the remaining functions of the life table (cumulate life-years free of disability expected to be lived at age x - $T_x^{SUL}$ and disease-free life expectancy at age x $e_x^{SUL}$, also named as health expectancy - $h_x$). Therefore, the life expectancy computed by the Sullivan method ($e_x^{SUL}$ or $h_x$) is an estimate of the morbidity-free life expectancy of the respective age-group.  

In the process of mortality transition, whilst mortality levels converge among populations, other public health indicators may still differ substantially. Hence, Sullivan's index for morbidity-free life expectancy can provide further insights to compare those groups with different health standards even though they exhibit similar mortality levels [@sullivan1971].

We evaluate the morbidity prevalence and compute morbidity-free life expectancies for some specific sets of morbidities grouped in 4 categories available from the two data sources:

  * Cardiovascular diseases - high blood pressure, high cholesterol, cerebrovascular accident [@pns2013]
  * Diabetes [@pns2013];
  * Osteopathies - arthritis, rheumatism, chronic spine problems (back pain, neck pain, etc), work-related musculoskeletal disorders (WMSD) [@pns2013];
  * Incapacities/disabilities: to walk, see or listen (restricted to severe or total incapacity) [@ibge2010];

Since differences in urban-rural mortality are expected to favor rural residents [@albuquerque2019], we compare both populations also by a relative measure of morbidity-free life expectancy. That is, we compute the proportion of life expectancy that the synthetic cohort is expected to live free from each related morbidity (${h_x}/{e_x}$ ratio). We adopt this strategy to compare relative measures and avoid distortions that might come from absolute values. We focus our attention to adult mortality differentials (15-69 age-groups) because PNS had disease prevalence data available only for adult population (18+)^[Even though PNS had prevalence data available only for adults aged over 18 years old, we considered the prevalence distribution of diseases for age group 15-19 equal to the rates observed for the age group 18-19. For age groups 0-14 the prevalence rates for PNS survey were considered equal to 0 in order to get estimates of morbidity-free life expectancy at birth.]. 

#### Decomposition of rural-urban DFLE differentials

Our decomposition approach is based on the stepwise replacement algorithm for decomposition of demographic measures developed by @andreev_etal2002. For equation 1, the estimation of person-years lived in good health, e. g., free of morbidity, requires two variable vectors: person-years lived by age group ($nL_x$), derived from age-specific mortality rates vector ($M_x$), and age-specific healthy condition or morbidity-free prevalences vector ($\Pi_x = (1 - _nP_x)$). Then, the health expectancy ($h_x$) at age x can be stated a function of age-specific mortality rates and age-specific health prevalences (equation 2).

$$h_x = h_x( M_x , \Pi_x )$$

The urban-rural differences for health expectancies can be decomposed into two components computed by applying the stepwise replacement algorithm. The algorithm's rationale lies behind the transformation of one population group vector of health expectancies ($h_x^{rur}$, for example) into the other population group vector of health expectancies ($h_x^{urb}$ in our case). Considering the components of $h_x$ function (equation 2), we can obtain rural health expectancy vector estimates out of urban health expectancy vector by transforming each of its elements $M_x^{rur}$ and $\Pi_x^{rur}$ into $M_x^{urb}$ and $\Pi_x^{urb}$ which is performed in an age-by-age replacement mode: $M^x$ and $\Pi^x$ are the mortality and moerbidity-free prevalence rates vectors composed by rates $m^{rur}_y$ and $\pi^{rur}_y$ at ages $x < y$ and $m^{urb}_y$ and $\pi^{urb}_y$ at ages $ x \geq y$, respectively [@andreev_etal2002].

Therefore, the difference $h_x^{rur} - h_x^{urb}$ is the sum of two components: 1) $\gamma_x^{rur-urb}$ (equation 3), component of $h_x$ difference due to difference in mortality rates at age x, and 2) $\lambda_x^{rur-urb}$ (equation 4), component of $h_x$ difference due to difference in morbidity-free prevalences at age x. 

$$ \gamma_x^{rur-urb} = \dfrac{1}{2} \Big[ [h_x(M^{x+1},\Pi^x)-h_x(M^{x},\Pi^x)] + [h_x(M^{x+1},\Pi^{x+1})-h_x(M^{x},\Pi^{x+1})]  \Big]$$

$$ \lambda_x^{rur-urb} = \dfrac{1}{2} \Big[ [h_x(M^{x},\Pi^{x+1})-h_x(M^{x},\Pi^{x})] + [h_x(M^{x+1},\Pi^{x+1})-h_x(M^{x+1},\Pi^{x})]  \Big]$$

## Results

### Urban-Rural mortality differentials

Figure 1 presents age-specific mortality rates by place of residence after death coverage correction by SEG-adjusted estimated DCRs. In consonance to the literature about rural-urban mortality differentials in Brazil and in other developing countries, the infant and child mortality rates are higher in rural areas than in urban areas and rural adult mortality rates are lower than urban adult mortality rates [@sastry2004;@gunther_harttgen2012;@fink_etal2016]. This compensatory effect of rural adult mortality advantage in relation to lower under-five mortality indicators results in the higher life expectancy estimates for rural populations, especially for males (table 2).   

[ FIGURE 1 : Rural and urban age-specific mortality rates by sex - Brazil, 2010. Source: Brazilian National Census 2010. ]

These adjusted mortality rates yields different life expectancy estimates from @albuquerque2019 (table 2). The author used the official life tables estimated for Brazil from IBGE for 2010 as reference to adjust the observed deaths from the 2010 census while we used the SEG-adjusted method taking in account regional differences in death coverage completeness. In this sense, our estimates resulted in higher life expenctancy at birth values, since two of the three most populated regions (Southeast - the most populated and South - the third most populated) have census death counts coverages close to completeness. The rural life expectancy advantage is more pronounced in males than in females and it gets higher for older ages. Female estimates do not show marked urban-rural differentials as male life expectancy estimates.

[ TABLE 1 : Rural and urban life expectancy estimates by sex and age - Brazil, 2010. Source: Brazilian national census 2010. ]

The sex differentials in mortality also favor females for Brazilian rural areas according to 2010 census data. Nevertheless, the female advantage in rural areas is lower than the urban female mortality advantage. Large differences from male/female mortality ratios are observed between rural and urban areas especially for adult ages. In this sense, the male mortality excess observed in Brazilian young adult males is more evident in urban areas and, in particular, in disadvantaged and suburban areas of cities [@pereira_queiroz2016;@pereira2018].  

### Urban-rural health conditions 

Urban and rural environments shape the life styles and type of work performed by each population. These environment differences have direct impacts on workers health [@moreira_etal2015]. Disadvantages in self-reported health conditions have been observed in rural populations in addition to their socioeconomic and transportation disadvantages to access public health equipment [@arruda_etal2018]. The difficulties to access health equipments due to distance or lack of resources were mentioned by 56\% of rural residents who did not access health services and needed to against 17\% of urban residents in the PNS survey of 2013. Urban residents mostly did not access health services when they needed to because of long waiting time (28\% against 8\% of rural population). Thus, these differentials in access to health services may incur in lower disease diagnosis. Indeed, PNS data shows that rural population had higher percentage of people that never had measured their glycemic levels (21\% against 10\% for urban residents) or blood pressure (6\% against 3\% for urban residents). This scenario could have been worse if the Family Health Strategy of the Brazilian Ministry of Health was not successful in reaching remote communities of the countryside of Brazil [@malta_etal2016;@albuquerque_etal2017;@bhalotra_etal2020]. Even though rural residents showed lower diagnosis rates than urban residents, we still had sufficient data to evaluate disease prevalence of urban and rural populations. 

For the adult population as a whole, there are rural penalties (higher rural-urban prevalence ratios) in prevalences of osteopathies and physical incapacities for males and of cardiovascular diseases and physical incapacities for females. Also, adult women fom rural environments had higher prevalence rates of all morbidities investigated. Figure 3 extends the analysis by age group. We present the prevalence rates estimated in the PNS survey of 2013 for cardiovascular diseases, diabetes and osteopathies and in the national census of 2010 for physical incapacities and their respective smoothed estimates^[Prevalence rates of diseases and disabilities were smoothed by apply the localy estimated scatterplot smoothing method (LOESS)]. The smoothing methods were used to minimize the high variability of prevalence rates, especially for PNS lower counts of rural residents. Smoothing of incapacities prevalence for census information are presented, but the original prevalence rates were used for Sullivan method estimation of next section, since they showed very low variability.  

[ FIGURE 3 : Rural and urban disease and disability prevalence by sex and age - Brazil, 2010-2013. Source: Brazilian National Census 2010 and National Health Survey 2013.]

As expected, rural males presented higher prevalence rates of osteopathies, especially in advanced ages. For women, there is no clear pattern due to high data variability for rural residents. On the opposite direction, rural men are in better off situation in regard to diabetes prevalence rates, which presented a wide gap for advanced ages, and also for cardiovascular diseases prevalence rates, which presented a small but contiuous gap from age group 30-34 onwards. Female prevalence curves for diabetes did not present any significant gap while the prevalence curves of cardiovascular diseases for women in rural areas exhibited higher rates than urban curves. For both males and females, the prevalence rates of physical disabilities declared in the national census of 2010 were slightly higher in rural settings. Hence, results are in conformity with previous analysis performed for rural workers in Brazil [@moreira_etal2015]. Significant decreases observed in PNS morbidities prevalence for the elderly may be related to poor disease diagnostic of this age-group in rural populations.

### Morbidity-free life expectancy

Table 2 presents the results of morbidity-free life expectancy or heath expectancy ($h_x$) estimates for males and females of rural and urban areas at birth, at 20 years old, at 40 years old and at 60 years old. For males, rural-urban disease-free life expectancy ratios show a continuous increase in the rural-urban gap through advanced ages. Indeed, these results corroborate to the idea of an existing urban mortality penalty in lower income countries and announces also a morbidity penalty for the urban elderly. These absolute values present worse scenarios in urban areas for life expectancy without cardiovascular diseases and without diabetes estimates. These two groups of diseases exhibited higher prevalences for the urban population for the adult and the older age groups. Female absolute values estimates reported negligible difference between urban and rural areas, even though a slight rural advantage was observed for diabetes-free life expectancy at ages 40 and 60. 

Absolute differences highlight rural advantages in mortality and morbidity indicators. We now turn our attention to relative differences in healthy life expectancy estimates, e. g., we evaluate the ratio of morbidity-free life expectancy by life expectancy ($h_x/e_x$ ratio) (table 2). This ratio can be interpreted as a proxy of the proportion of life expected to be lived free from morbidity for a synthetic cohort with a set of age-specific morbidity prevalence rates and age-specific mortality rates. Relative estimates of health expectancy changes the rural advantage observed for all groups of morbidity so far. The rural advantage prevails only for cardiovascular diseases and diabetes whereas a relative urban advantage is observed for osteopathies and physical disabilities. These results confirms that rural residents are more prone to develop physical incapacities and disabilities and suffer of musculoskeletal pain due to the physically demanding labour required in agriculture [@maia_rodrigues2010;@moreira_etal2015]. The absolute advantages observed in health expectancy numbers may not reflect in actually better life conditions in terms of life span relative measures. Therefore, we decompose differences in health expectancy into its mortality and morbidity components to investigate positive or negative contributions and provide further evidence on what might seem as a mortality exclusive advantage or mortality and morbidity advantage of rural residents.     

[ TABLE 2 : Rural and urban health expectancy estimates and health expectancy to life expecanty ratios by sex and age - Brazil, 2010-2013. Source: Brazilian National Census 2010 and National Health Survey 2013. ]

### Decomposition of health expectancies

Figure 3 presents the results of decompositions of health expectancies by geographic area and related morbidity. For males, positive values of mortality contribution to rural-urban health expectancies differentials shows that the overall mortality curve differences among rural and urban populations favors the first ones. However, as expected by morbidity prevalence curves, ostheopaties and physical disabilites have negative impacts on the health expectancies differences between rural and urban populations. These differences are, however, lower than the differences of the overall mortality shape. Hence, positive differences in rural-urban health differentials are still evident even though some morbidities act towards reduction of rural advantages. 

Estimated differences from rural to urban morbidity-free life expectancies at 20 years old of these two morbidities resulted in a 0.5 difference for osteopathies and 2.4 for physical disabilities. For osteopathies, the disease prevalence profiles difference accounted for -2.4 of the estimated difference and the mortality shape differences accounted for 2.9 of the differences. Therefore, muscoeskeletal and physical morbidities are responsible for slowing down the rural mortality curve advantaged condition. For census reported disabilities, the difference in morbidity profiles accounted for -0.5 of rural-urban health expectancy difference, much lower than morbidity contribution of osteopathies, but also in the opposite direction of the mortality profiles difference contribution. 

This decomposition exercise highlights that health expectancy differences observed between rural and urban populations are not only due to overall mortality difference but also related to differences of age-specific morbidity prevalence. The results are in consonance with the bibliographic review, which show that cardiovascular diseases and diabetes are city related morbidities and physical disabilities and osteopathies are rural related morbidities that result from physicaly harming work performed at rural areas. Hence, rural residents present a double advantage (in mortality and in morbidity) when we compare health expectancies for cardiovascular diseases and diabetes, however, this advantage becomes exclusively a mortality profile advantage when we decompose differences for osteopathies and physical disabilities.

For women, cardiovascular diseases and diabetes prevalences seems to damage the health expectancies of urban elderly, but minor differentials were found among physical or muscoeskeletal related morbidities. However, we must evaluate this results with caution, since there is a lower diagnosis of morbidities in rural areas due to lack of measurement and lower quality of reported information on the elderly.

[FIGURE 3: Decomposition of rural-urban health expectancy differentials by sex and age - Brazil, 2010-2013. Source: Brazilian National Census 2010 and National Health Survey 2013.]

## Discussion

This paper extended the discution on rural-urban mortality towards health expectancy differentials. Mortality differencials have already been addressed in previous researches [@carvalho_wood1978;@albuquerque2019;@pereira2020] and our results reflect those previous fidings. The main contribution of the paper was to look into health expectancies differentials based on available age-specific prevalence data of the PNS survey of 2013 and evaluate this estimates relative to life expectancy estimates and decompose differences into mortality shape difference contribution and morbidity profiles contribution.

<!-- Recent fidings suggest that obseved mortality differences in between urban and rural areas are due to socioeconomic inequalities and higher mortality in deprived urban areas [@pereira2020]. Several papers suggest that under same socioeconomic conditions of urban counterparts, rural dwellers would report better health conditions [@maia_rodrigues2010] or even lower infant mortality rates [@sastry2004]. Several works have documented that higher rates of poor health statement by rural household respondents are related to health illiteracy and lower schooling levels [@viacava_etal2019]. -->

Over the last 30 years, Brazil has experienced substantial changes on its public health policy represented by the implementation and consolidation of the country's unified health system (SUS) [@castro_etal2019]. SUS guaranteed a massive expansion of the health care assistance for the most vulnerable social groups through an universal and free of charges health services. Moreover, the gradual implementation of the family health strategy (ESF), a public health policy approach focused on primary care at the community level, provided several positive outcomes such as the reduction of infant mortality rates [@macinko_etal2006;@aquino_etal2009;@rocha_soares2010;@bhalotra_etal2020], improvement of child health [@santos_jacinto2017], reduction of maternal mortality rates [@bhalotra_etal2020] and reduction of hospitalizations due to causes sensitive to primary care [@pimenta_etal2018]. ESF positive outcomes were mostly visible in regions and areas of the country with worsened health and socioeconomic conditions, pointing up its orientation towards the most vulnerable social groups, poorest regions and local communities [@rocha_soares2010;@guimaraes2018]. Additionaly, ESF community-level policy provides other positive spillover effects on other socioeconomic variables such as education and employement [@rocha_soares2010].  

In 2013, 54.4% of Brazilian households were registered in the local family health unit, 74.9% of rural households and 50.6% of urban households [@malta_etal2016]. This higher ESF coverage and primary care assistance in rural areas might account for the favorable results of rural residents in regard to mortality and cardiovascular diseases and diabetes morbidity differentials, since ESF professionais provide not only health care support, but also health information, enhancing health literacy levels of local communities.

The differences of health expectancies observed in diet related morbidities (cardiovascular diseases and diabetes) also highlight cultural differences of living conditions in rural and urban settings, especially in regard to different diets. In the developing world, diet changes led to higher consumption of fat and sugar and resulted in the increase of excess weight in populations from both urban and rural (in a lower extent) settings [@mendez_popkin2004]. In Brazil, higher consumption of ultra-processed food is associated with higher prevalence of obesity and excess weight [@canella_etal2014] and it has been increasing through time [@martins_etal2013]. Also, ultra-processed food consumption increases among higher income households and usually deteriorates the quality of a diet [@louzada_etal2018;@simoes_etal2018]. In general, urban household diets in Brazil relies on supermarket food and present large shares of processed foods whereas rural diets have considerable shares of local and minimally processed food on its composition [@nardoto_etal2006;@nardoto_etal2011]. However, there is strong evidence that the on-going nutritional transition in some rural communities in Brazil is leading to a higher supermarket dependence on food consumption, resulting in lower demand local and unprocessed foods [@figueiredo_etal2015;@rodrigues_etal2016]. In this sense, public health policies and especially family health professionals must take into account this changing diet movement in order to avoid an increase of processed food non-communicable diseases such as cardiovascular diseases and diabetes in rural communities.

FALAR de diferenças por osteopatias!

The results of this work support the efforts of family health strategy towards health coverage of most vulnerable areas of the country [@guimaraes2018]. ESF expansion provides diagnosis and follow-up of chronic diseases in rural populations and provides and enhancement of its health literacy which might also have contributed for further mortality improvements of this groups (citar). Also, life styles seem to play a key role in lower mortality observed in rural areas, attached to lower exposition to urban-related mortality causes such as violence and accidents (citar).

This paper results should be analyzed with caution. As mentioned, rural population lower access to health services reflects in lower diagnostic rates of health indicators such as glycemic level and blood pressure. Then, prevalence rates for rural groups might be underestimated due to lack of diagnosis. In spite of this important detail, the data collected is robust enough and results are in consonance with previous studies on rural and urban health and mortality differentials. We verified the existence of an urban adult mortality penalty and also in an urban adult morbidity penalty for cardiovascular diseases and diabetes. Finally, we verified a rural morbidity penalty related to physical incapacities (to walk, see and listen) and osteopathies. This penalty contributes for lower health expectancy differences in regard to these two morbidities, but it is compensated by the rural mortality advantage. Therefore, rural residents exhibit higher life expecancies, but a significant share of this life expectancy is co-occur with physical and muscoeskeletal related morbidities.

## References

